#!/usr/bin/env bash
# Build a single Darktec official firmware (on-demand / custom advert name / radio).
#
# Required env:
#   FIRMWARE_VERSION   e.g. v1.17.1  (commit suffix added as -od{sha8})
#   DARKTEC_PIO_ENV    e.g. Darktec_repeater
#   DARKTEC_ROLE_SLUG  e.g. repeater
#   BATTERY_CHEMISTRY  e.g. BATTERY_CHEM_LIION
#   BATTERY_CELLS      e.g. 1
#   CHEM_SLUG          e.g. liion
#
# Optional:
#   ADVERT_NAME        node name string (default depends on role / platformio.ini)
#   NAME_SLUG          sanitized slug for filename (default: default)
#   LORA_FREQ          MHz (default 869.075)
#   LORA_BW            kHz (default 62.5)
#   LORA_SF            5–12 (default 8)
#   LORA_CR            5–8 (default 8)
#   LORA_TX_POWER      dBm (default 22)
#
# Output:
#   out/DarktecOff_{role}_{chem}_{cells}s__{name_slug}__{radio_slug}__{sha}.{uf2,zip}
#
# No DARKTEC_BATT_PROTECT — official variant has no ADC cutoff.
# Do NOT put battery/LORA overrides as -U/-D in PLATFORMIO_BUILD_FLAGS.
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
cd "$ROOT"

: "${FIRMWARE_VERSION:?}"
: "${DARKTEC_PIO_ENV:?}"
: "${DARKTEC_ROLE_SLUG:?}"
: "${BATTERY_CHEMISTRY:?}"
: "${BATTERY_CELLS:?}"
: "${CHEM_SLUG:?}"

COMMIT_HASH="$(git rev-parse --short=8 HEAD)"
FIRMWARE_VERSION_STRING="${FIRMWARE_VERSION}-od${COMMIT_HASH}"
NAME_SLUG="${NAME_SLUG:-default}"
NAME_SLUG="$(echo "$NAME_SLUG" | tr '[:upper:]' '[:lower:]' | sed -E 's/[^a-z0-9]+/-/g; s/^-+//; s/-+$//; s/^$/default/' | cut -c1-24)"

LORA_FREQ="${LORA_FREQ:-869.075}"
LORA_BW="${LORA_BW:-62.5}"
LORA_SF="${LORA_SF:-8}"
LORA_CR="${LORA_CR:-8}"
LORA_TX_POWER="${LORA_TX_POWER:-22}"

DEFAULT_FREQ="869.075"
DEFAULT_BW="62.5"
DEFAULT_SF="8"
DEFAULT_CR="8"
DEFAULT_TX="22"

radio_token() {
  printf '%s' "$1" | tr '.' 'p' | tr -cd 'A-Za-z0-9p-'
}
RADIO_SLUG="f$(radio_token "$LORA_FREQ")-bw$(radio_token "$LORA_BW")-sf${LORA_SF}-cr${LORA_CR}-tx${LORA_TX_POWER}"

OUT_BASE="DarktecOff_${DARKTEC_ROLE_SLUG}_${CHEM_SLUG}_${BATTERY_CELLS}s__${NAME_SLUG}__${RADIO_SLUG}__${COMMIT_HASH}"

rm -rf out
mkdir -p out

RADIO_CUSTOM=0
if [ "$LORA_FREQ" != "$DEFAULT_FREQ" ] || \
   [ "$LORA_BW" != "$DEFAULT_BW" ] || \
   [ "$LORA_SF" != "$DEFAULT_SF" ] || \
   [ "$LORA_CR" != "$DEFAULT_CR" ] || \
   [ "$LORA_TX_POWER" != "$DEFAULT_TX" ]; then
  RADIO_CUSTOM=1
fi

DEFS_H="${ROOT}/.pio/darktec_ondemand_defs.h"
QUIET_H="${ROOT}/variants/darktec/build_quiet.h"
mkdir -p "$(dirname "$DEFS_H")"
python3 - "$DEFS_H" "${FIRMWARE_VERSION_STRING}" "${ADVERT_NAME:-}" \
  "${BATTERY_CHEMISTRY}" "${BATTERY_CELLS}" \
  "${RADIO_CUSTOM}" "${LORA_FREQ}" "${LORA_BW}" "${LORA_SF}" "${LORA_CR}" "${LORA_TX_POWER}" <<'PY'
import sys
(
    path, ver, advert,
    chem, cells,
    radio_custom, freq, bw, sf, cr, tx,
) = sys.argv[1:12]

def c_str(s: str) -> str:
    return '"' + s.replace("\\", "\\\\").replace('"', '\\"').replace("\n", " ").replace("\r", "")[:31] + '"'

lines = [
    "#pragma once",
    "/* Generated by scripts/build-darktec-ondemand.sh — do not edit */",
    "",
    "/* Battery chemistry for UI % only — no ADC protect on official. */",
    "#undef BATTERY_CHEMISTRY",
    f"#define BATTERY_CHEMISTRY  {chem}",
    "#undef BATTERY_CELLS",
    f"#define BATTERY_CELLS  {cells}",
    "",
    "#undef FIRMWARE_VERSION",
    f"#define FIRMWARE_VERSION {c_str(ver)}",
]

if advert.strip():
    lines += [
        "#undef ADVERT_NAME",
        f"#define ADVERT_NAME {c_str(advert.strip())}",
    ]

if radio_custom == "1":
    lines += [
        "",
        "#define DARKTEC_RADIO_CUSTOM 1",
        "#undef LORA_FREQ",
        f"#define LORA_FREQ  {freq}",
        "#undef LORA_BW",
        f"#define LORA_BW  {bw}",
        "#undef LORA_SF",
        f"#define LORA_SF  {sf}",
        "#undef LORA_CR",
        f"#define LORA_CR  {cr}",
        "#undef LORA_TX_POWER",
        f"#define LORA_TX_POWER  {tx}",
    ]

open(path, "w", encoding="utf-8").write("\n".join(lines) + "\n")
print(f"Wrote {path} (radio_custom={radio_custom})")
PY

export PLATFORMIO_BUILD_FLAGS="-DCFG_DEBUG=0 -include ${QUIET_H} -include ${DEFS_H}"

echo "=== On-demand official build ${OUT_BASE} ==="
echo "env=${DARKTEC_PIO_ENV} chem=${BATTERY_CHEMISTRY} cells=${BATTERY_CELLS} name=${ADVERT_NAME:-<default>}"
echo "radio freq=${LORA_FREQ} bw=${LORA_BW} sf=${LORA_SF} cr=${LORA_CR} tx=${LORA_TX_POWER} custom=${RADIO_CUSTOM}"
echo "PLATFORMIO_BUILD_FLAGS=${PLATFORMIO_BUILD_FLAGS}"
cat "$DEFS_H"

pio run -e "${DARKTEC_PIO_ENV}"

python3 bin/uf2conv/uf2conv.py \
  ".pio/build/${DARKTEC_PIO_ENV}/firmware.hex" \
  -c \
  -o ".pio/build/${DARKTEC_PIO_ENV}/firmware.uf2" \
  -f 0xADA52840

cp -f ".pio/build/${DARKTEC_PIO_ENV}/firmware.uf2" "out/${OUT_BASE}.uf2"
if [ ! -f ".pio/build/${DARKTEC_PIO_ENV}/firmware.zip" ]; then
  echo "ERROR: missing OTA firmware.zip"
  exit 1
fi
cp -f ".pio/build/${DARKTEC_PIO_ENV}/firmware.zip" "out/${OUT_BASE}.zip"

echo "Wrote out/${OUT_BASE}.uf2 and .zip"
ls -la out/
